title: NORDEN II
description: Tactical Dossier and Ballistics Database
remote_theme: pages-themes/midnight@v0.2.0

url: "https://KJumpmaster.github.io"
baseurl: "/home"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
